### ISSUE TITLE
Installation problem in Indigo/Microsoft Windows Server 2003/Unable to create a new web application project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#101]
```
Hello
I installed eclipse 3.7 (indigo) and the google plugin, and when i am trying to 
create my first Web application i have this error:

The selected wizard could not be started.
Plug-in com.google.gdt.eclipse.suite was unable to load class 
com.google.gdt.eclipse.suite.wizards.NewWebAppProjectWizard.
An error occurred while automatically activating bundle 
com.google.gdt.eclipse.suite (810).  
I am using Google Suite Plugin 3.1.3, my Os is a Microsoft windows server 2003 
installed in a virtual machine
```

Original issue reported on code.google.com by `sofiene....@gmail.com` on 6 Feb 2013 at 9:48

**Comment by GoogleCodeExporter** [comment]
```
Take a look at Window -> Show View -> Error Log. What do you see?
```

Original comment by `rdayal@google.com` on 20 Feb 2013 at 2:44

**Comment by GoogleCodeExporter** [comment]
```
I see errors :D
well here is my log:

--------------------------------------------------------------------------------
------
null
Error
Wed Feb 20 16:00:43 CET 2013
Failed to execute item com.google.gdt.eclipse.suite.newWebAppProject

org.eclipse.core.commands.NotHandledException: There is no handler to execute 
for command com.google.gdt.eclipse.suite.newWebAppProject
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:485)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.ui.internal.handlers.HandlerService.executeCommand(HandlerService.java:169)
    at org.eclipse.ui.internal.handlers.SlaveHandlerService.executeCommand(SlaveHandlerService.java:241)
    at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:829)
    at org.eclipse.ui.menus.CommandContributionItem.access$19(CommandContributionItem.java:815)
    at org.eclipse.ui.menus.CommandContributionItem$5.handleEvent(CommandContributionItem.java:805)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4165)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3754)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
--------------------------------------------------------------------------------
-----
```

Original comment by `sofiene....@gmail.com` on 20 Feb 2013 at 3:05

**Comment by GoogleCodeExporter** [comment]
```
Can you try launching in a new workspace and tell me if you see anything else 
appear in the logs?

Also, can you tell me what version of the com.google.gdt.* plugins you see in 
your installation?

If you navigate to the plugins directory of your Eclipse installation, and do a 
ls for all plugins that start with com.google.gdt.*, what does the listing look 
like?
```

Original comment by `rdayal@google.com` on 5 Mar 2013 at 6:39

**Comment by GoogleCodeExporter** [comment]
```
I am seeing this same issue but on Indigo/Ubuntu 12.10.  

Using com.google.gdt.eclipse.core_3.2.2.v201303261859-rel-r42.jar

Opening in a new workspace resolved it, but I want to keep my old workspace, 
and I only want to have one total workspace.  Some sort of non-forward 
compatible setting...?
```

Original comment by `e...@ejahn.net` on 18 Apr 2013 at 8:16
