### ISSUE TITLE
Errors running builder 'Google App Engine Project Change Notifier' on project 'fourhour'. java.lang.NullPointerException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#116]
```
What steps will reproduce the problem?

1. download the test case project
git clone https://github.com/renfeng/fourhour

2. import into eclipse as maven project (m2eclipse version 0.12.1.20110112-1712)

3. from project properties > java build path > libraries, add library, double 
click google app engine, leave it to use default sdk, my version is 1.7.5

4. from project properties > java build path > order and export, move maven 
dependencies to the bottom (after app engine sdk). see attachment, 
eclipse-order-and-export.png

5. from project properties > google > app engine, enable the option of use 
google app engine. see attachment, eclipse-gae-settings.png

6. clean build the project. when the build is finished (the build is 
successful, though) an error message is shown, attachment 
eclipse-error-message.png

What is the expected output? What do you see instead?
It's expected to see nothing after a successful clean build. But, it shows an 
error message.

What version of the product are you using? On what operating system?
Please read Session Data at the very bottom.

Please provide any additional information below.

i've read issue 90, 
https://code.google.com/p/google-plugin-for-eclipse/issues/detail?id=90, and 
followed the comment 19, 
https://code.google.com/p/google-plugin-for-eclipse/issues/detail?id=90#c19. 
nothing worked. i guess my problem is a little different.

Here is the details copied from Eclipse Error Log.

Message:
Errors running builder 'Google App Engine Project Change Notifier' on project 
'<project name>'.

Exception Stack Trace:
java.lang.NullPointerException
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmServiceCreator.deleteAllConfigs(SwarmServiceCreator.java:454)
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmServiceCreator.create(SwarmServiceCreator.java:312)
    at com.google.gdt.eclipse.appengine.swarm.wizards.HandleGaeProjectChange.gaeProjectRebuilt(HandleGaeProjectChange.java:75)
    at com.google.appengine.eclipse.core.properties.ui.GaeProjectChangeNotifier.build(GaeProjectChangeNotifier.java:88)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:629)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:172)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:203)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:255)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:258)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:362)
    at org.eclipse.core.internal.resources.Project$1.run(Project.java:545)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1975)
    at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:524)
    at org.eclipse.core.internal.resources.Project.build(Project.java:115)
    at com.google.gdt.eclipse.core.BuilderUtilities$2.runInWorkspace(BuilderUtilities.java:202)
    at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Session Data:
eclipse.buildId=M20110210-1200
java.version=1.6.0_27
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.reporting.product
Command-line arguments:  -data /home/renfeng/workspace-truemuze -os linux -ws 
gtk -arch x86_64 -product org.eclipse.epp.package.reporting.product

```

Original issue reported on code.google.com by `renfeng...@gmail.com` on 8 Apr 2013 at 3:48

Attachments:
- [eclipse-gae-settings.png](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-116/comment-0/eclipse-gae-settings.png)
- [eclipse-order-and-export.png](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-116/comment-0/eclipse-order-and-export.png)
- [eclipse-error-message.png](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-116/comment-0/eclipse-error-message.png)

**Comment by GoogleCodeExporter** [comment]
```
I don't think you should specify the name of the test case project in the title 
of this issue - surely the problem is broader then that.
```

Original comment by `t...@malcolmson.ca` on 8 Apr 2013 at 3:54

**Comment by GoogleCodeExporter** [comment]
```
Here is a screenshot of the plugins installed (with version info).
```

Original comment by `renfeng...@gmail.com` on 8 Apr 2013 at 3:55

Attachments:
- [eclipse-plugins.png](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-116/comment-2/eclipse-plugins.png)

**Comment by GoogleCodeExporter** [comment]
```
Thanks. I guess people wouldn't search the topic with their project names :D

They probably make searches like this, "Errors running builder 'Google App
Engine Project Change Notifier' on project"
"java.lang.NullPointerException"<https://www.google.com/search?q=%22Errors+runni
ng+builder+'Google+App+Engine+Project+Change+Notifier'+on+project%22+%22java.lan
g.NullPointerException%22&aq=f&oq=%22Errors+running+builder+'Google+App+Engine+P
roject+Change+Notifier'+on+project%22+%22java.lang.NullPointerException%22&aqs=c
hrome.0.57.8626j0&sourceid=chrome&ie=UTF-8>


On Mon, Apr 8, 2013 at 11:54 PM,
<google-plugin-for-eclipse@googlecode.com>wrote:
```

Original comment by `renfeng...@gmail.com` on 8 Apr 2013 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
I confirm that I'm having the same issue.
```

Original comment by `m4des...@gmail.com` on 11 Apr 2013 at 12:22

**Comment by GoogleCodeExporter** [comment]
```
Thanks for following up. It helps to get more attention, and solved as soon.


On Thu, Apr 11, 2013 at 8:22 AM,
<google-plugin-for-eclipse@googlecode.com>wrote:
```

Original comment by `renfeng...@gmail.com` on 11 Apr 2013 at 12:49

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this.  We've isolated the issue, we're working on a fix.

Appu
```

Original comment by `a...@google.com` on 11 Apr 2013 at 8:29

**Comment by GoogleCodeExporter** [comment]
```
Thank you. It was fast. Good job.


On Fri, Apr 12, 2013 at 4:30 AM,
<google-plugin-for-eclipse@googlecode.com>wrote:
```

Original comment by `renfeng...@gmail.com` on 11 Apr 2013 at 11:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 15 Apr 2013 at 3:37
- Added labels: **Release-3.2.3**

**Comment by GoogleCodeExporter** [comment]
```
So for now, one option is to disable the "Google App Engine Project Change 
Notifier" in the "Project->Properties->Builders" section.  If you're not using 
Endpoints in AppEngine, this builder can be disabled.

```

Original comment by `a...@google.com` on 18 Apr 2013 at 9:16

**Comment by GoogleCodeExporter** [comment]
```
No. I'm not using Endpoints. I've read that I could disable the builder.
However, it really helps that you can point out what will be affected by
doing that. Thanks.


On Fri, Apr 19, 2013 at 5:16 AM,
<google-plugin-for-eclipse@googlecode.com>wrote:
```

Original comment by `renfeng...@gmail.com` on 19 Apr 2013 at 12:37

**Comment by GoogleCodeExporter** [comment]
```
The builder is used to edit the web.xml file for endpoints configuration and to 
create some endpoints related files (.api, .discovery) from 
@Api(com.google.api.server.spi.config.Api) annotated classes.  These are 
descriptions of the endpoint used to expose the endpoint when you deploy your 
application, they are also used to generate the java client libraries if you 
have an attached android project.  Since you're not using endpoints, the 
builder does nothing for you.
```

Original comment by `a...@google.com` on 19 Apr 2013 at 3:38

**Comment by GoogleCodeExporter** [comment]
```
Ive noticed that I cant even enable the "Google App Engine Project Change 
Notifier" builder. I check the box and click Ok to close the dialog, then 
reopen the dialog and it's unchecked again.

I'm getting the NullPointerException during builds as well.
Using:
Juno (Service Release 2)
OS X Mountain Lion 
GPE (Google Plugin for Eclipse 4.2 3.2.2.v201303261859-rel-r42)
GAE 1.7.7.1


```

Original comment by `bposs...@gmail.com` on 21 Apr 2013 at 8:47

**Comment by GoogleCodeExporter** [comment]
```
H, seeing the same issue - and I have "Google App Engine Project Change 
Notifier" unticked...?

Message:
Errors running builder 'Google App Engine Project Change Notifier' on project 
'<project name>'.

Exception Stack Trace:
java.lang.NullPointerException
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmServiceCreator.deleteAllConfigs(SwarmServiceCreator.java:454)
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmServiceCreator.create(SwarmServiceCreator.java:312)
    at com.google.gdt.eclipse.appengine.swarm.wizards.HandleGaeProjectChange.gaeProjectRebuilt(HandleGaeProjectChange.java:75)
    at com.google.appengine.eclipse.core.properties.ui.GaeProjectChangeNotifier.build(GaeProjectChangeNotifier.java:88)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:726)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

Session Data:
eclipse.buildId=3.2.0.201303060821-RELEASE-e42
java.version=1.6.0_43
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product 
org.springsource.sts.ide
```

Original comment by `ADO...@gmail.com` on 21 Apr 2013 at 11:31

**Comment by GoogleCodeExporter** [comment]
```
@bpossolo: That's odd. Can you check the Error Log (Window -> Show View -> 
Error Log) to see if any exceptions happen after you try and untick the builder 
and hit 'Ok/Apply'? Also, can you post the contents of your .project file (when 
the builder is in the unticked state)? You can also send it to appu and I 
directly.

@ADOB63: Would you be able to do the same (send the contents of your .project 
file)?

As a more heavy-handed approach, you can open up your .project file and remove 
the following entry:

<buildCommand>
            <name>com.google.appengine.eclipse.core.gaeProjectChangeNotifier</name>
            <arguments>
            </arguments>
</buildCommand>

Save the .project file, and refresh your project.



```

Original comment by `rdayal@google.com` on 22 Apr 2013 at 2:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 26 Apr 2013 at 8:15
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Yay! I updated to the latest version of the GPE plugin and I no longer get the 
error! Thank you so much!
```

Original comment by `bposs...@gmail.com` on 27 Apr 2013 at 5:39
