### ISSUE TITLE
Unexpected error while validating "MyTaskBean.java"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#197]
```
What steps will reproduce the problem?
1. While running GPE

MyTaskBean.java is a java source file in a GWT project.


What version of the product are you using? On what operating system?

Eclipse 4.2.2, GEP 3.2.0

Please provide any additional information below.

I got this stack trace:

!ENTRY com.google.gdt.eclipse.appengine.rpc 4 0 2013-05-06 10:17:16.880
!MESSAGE Unexpected error while validating MyTaskBean.java
!STACK 0
java.lang.NullPointerException
    at com.google.gdt.eclipse.appengine.rpc.validators.JavaCompilationParticipant.buildStarting(JavaCompilationParticipant.java:83)
    at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.notifyParticipants(AbstractImageBuilder.java:566)
    at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:288)
    at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:134)
    at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:265)
    at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:193)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:726)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

Original issue reported on code.google.com by `udo.wal...@abas.de` on 7 May 2013 at 9:23

**Comment by GoogleCodeExporter** [comment]
```
I'm seeing a lot of these errors in my project too.  I don't even have the 
AppEngine SDK installed - is this perhaps why it happens?
```

Original comment by `carch...@gmail.com` on 11 Jul 2013 at 7:51

**Comment by GoogleCodeExporter** [comment]
```
Hi,
I also see a lot of these using Eclipse 3.8 or Eclipse 4.3.1.

For instance, just got this one:

eclipse.buildId=M20130131-0800
java.version=1.6.0_20
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=fr_FR
Framework arguments:  -Xms384m -Xmx1024m -XX:MaxPermSize=256m -showlocation
Command-line arguments:  -os win32 -ws win32 -arch x86 -Xms384m -Xmx1024m 
-XX:MaxPermSize=256m -showlocation

Error
Wed Dec 11 18:41:01 CET 2013
Unexpected error while validating CloseAction.java

java.lang.NullPointerException
    at com.google.gdt.eclipse.appengine.rpc.validators.JavaCompilationParticipant.buildStarting(JavaCompilationParticipant.java:83)
    at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.notifyParticipants(AbstractImageBuilder.java:566)
    at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:288)
    at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:60)
    at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:254)
    at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:173)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:726)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)



Is anybody looking into this issue ????

There are currently 163 open issues, of which 47 including this one are 
unaccounted yet. Seeing this one is 6 months old, I would think someone would 
have looked into it already, or given some advice as to the possible cause of 
this kind of error ?


```

Original comment by `ldena...@gmail.com` on 11 Dec 2013 at 5:52

**Comment by GoogleCodeExporter** [comment]
```
Also seeing a lot of these while building the same, multi-module Maven GWT 
project:

eclipse.buildId=M20130131-0800
java.version=1.6.0_20
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=fr_FR
Framework arguments:  -Xms384m -Xmx1024m -XX:MaxPermSize=256m -showlocation
Command-line arguments:  -os win32 -ws win32 -arch x86 -Xms384m -Xmx1024m 
-XX:MaxPermSize=256m -showlocation

Error
Wed Dec 11 18:44:06 CET 2013
Unexpected error while validating package-info.java

java.lang.NullPointerException
    at com.google.gdt.eclipse.appengine.rpc.validators.JavaCompilationParticipant.buildStarting(JavaCompilationParticipant.java:83)
    at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.notifyParticipants(AbstractImageBuilder.java:566)
    at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:288)
    at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:60)
    at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:254)
    at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:173)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:726)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)



Using Eclipse 3.8.2 with GPE 3.2.3.v201304260926-rel-r42
(I believe this is the latest release f GPE available for the Juno Eclipse 
branch)


```

Original comment by `ldena...@gmail.com` on 11 Dec 2013 at 6:03

**Comment by GoogleCodeExporter** [comment]
```
Could you guys update to the latest version of GPE? The current version is 
3.4.2. We no longer ship the appengine.rpc plugin at all, so this error should 
go away. Could you try updating?
```

Original comment by `rdayal@google.com` on 11 Dec 2013 at 6:36

**Comment by GoogleCodeExporter** [comment]
```
Hi and many thanks for the quick reply.

I confirm that upgrading to version 3.4.2 of the GPE solved these issues.

Many thanks for your help!

```

Original comment by `ldena...@gmail.com` on 20 Dec 2013 at 12:14

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 20 Dec 2013 at 9:05
- Changed state: **WontFix**
