### ISSUE TITLE
GWT Designer (2.5.1) won't be able to create the war from the project in Eclipse.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#201]
```
What steps will reproduce the problem?
1. Create a GWT project with GWT Designer plugin
2. Right click on the gwt module xml file
3. Select Google Web Toolkit -> Deploy Module
4. Select a disk location and Click OK.
5. Deployment failed with the following error details

Plug-in Provider: Google
Plug-in Name: 
Plug-in ID: org.eclipse

java.lang.ClassNotFoundException: 
org.eclipse.jdt.launching.IJavaLaunchConfigurationConstants
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:506)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction.getGWTProjectClasspath(DeployModuleAction.java:364)
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction.createBuildScript(DeployModuleAction.java:150)
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction.access$1(DeployModuleAction.java:131)
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction$1.run(DeployModuleAction.java:103)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

Full stack trace (to see full context):
java.lang.reflect.InvocationTargetException
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction$1.run(DeployModuleAction.java:114)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: java.lang.NoClassDefFoundError: 
org/eclipse/jdt/launching/IJavaLaunchConfigurationConstants
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction.getGWTProjectClasspath(DeployModuleAction.java:364)
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction.createBuildScript(DeployModuleAction.java:150)
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction.access$1(DeployModuleAction.java:131)
    at com.google.gdt.eclipse.designer.actions.deploy.DeployModuleAction$1.run(DeployModuleAction.java:103)
    ... 1 more
Caused by: java.lang.ClassNotFoundException: 
org.eclipse.jdt.launching.IJavaLaunchConfigurationConstants
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:506)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 5 more



What is the expected output? What do you see instead?

GWT Design compiles and create a war file in the location selected

What version of the product are you using? On what operating system?

Eclipse 3.6 
GWT SDK 2.5.1 with GWT Designer
JDK 1.6

Please provide any additional information below.

org.eclipse.jdt.launching is in the Eclipse install, but GWT Designer is not 
able to find it.

I also tried Eclipse 3.7 with the corresponding GWT.  Samething.
```

Original issue reported on code.google.com by `colin.y....@gmail.com` on 14 May 2013 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
This is on Windows 8.
```

Original comment by `colin.y....@gmail.com` on 14 May 2013 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
This usually indicates corrupted installation. Try to re-install into new 
(clean) Eclipse instance.
```

Original comment by `alexande...@gmail.com` on 20 May 2013 at 5:26

**Comment by GoogleCodeExporter** [comment]
```
Alex:

This is a new eclipse, GWT SDK and Designer install.  I tried both 3.6 and 3.7 
versions.  Others reported the same issue on the forum.

Colin
```

Original comment by `colin.y....@gmail.com` on 21 May 2013 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
did you find a solution?

```

Original comment by `mmari...@gmail.com` on 16 Jun 2013 at 8:13

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem. Anyone found a solution?
```

Original comment by `galletti...@gmail.com` on 21 Jun 2013 at 10:46

**Comment by GoogleCodeExporter** [comment]
```
I solved this by complete uninstalling both GWT Designer and WindowBuilder 
(c-o-m-p-l-e-t-e!) and then installing them both at once from here: 
https://developers.google.com/web-toolkit/tools/download-gwtdesigner Choose the 
appropriate version, for 4.2 use 
http://dl.google.com/eclipse/inst/d2gwt/latest/4.2 (the link is missing but it 
works).

There are big differences in designer's versions that aren't well explained 
anywhere. One version is GPE edition, it comes with the plugin from the same 
repo. I doesn't have "Google Web Toolkit" menu, doesn't allow to enable/disable 
using WebKit, doesn't have designer width/height setting and so on. It also 
places its settings under Google menu in Eclipse preferences. And it's newer, 
3.1.2 for now. People often get confused when they ask how to build WAR and 
they're told to choose "Google Web Toolkit — Deploy module" and they wonder 
where this option is. Surprise, they have this GPE edition which lacks this 
function for whatever reason! Sometimes I suspect that I'm the only one on this 
planet who figured it out.

The other version has its own repo as I mentioned before. It's older (2.6.0), 
requires the exact WindowBuilder version (shipped together with the designer) 
and has much more features like building WAR, setting the preview size etc. 
Though if you'll install it you have to stick to WB 1.5.0 or 1.5.2, any newer 
version leads to various exceptions. Both versions are quite buggy, at least on 
Linux, lol. Since we have nothing better we should deal with it.

Anyway, I stronlgy suggest you learn maven instead of using this unreliable 
feature. I know, it's a big step and it's a bit harder to configure and 
understand but you'll get great advantages using maven especially if you plan 
to distribute your app with sources to other people. They would only have to 
run "mvn package" to get the WAR without installing Eclipse, all needed 
libraries by hand and the full environment! You also won't have to bring all 
those 3rd party libs along with your project, maven will download them and add 
to the classpath automatically. I use m2e for Eclipse integration and it works 
fine. Ah, and the best part: when you build your WAR maven (to be precise, 
gwt-maven-plugini) runs permutations compilers in parallel while the standart 
WAR builder runs them sequentially. The building time is reduced by the time of 
cores you have! A killer feature, don't you think?
```

Original comment by `radioano...@gmail.com` on 30 Jun 2013 at 7:50

**Comment by GoogleCodeExporter** [comment]
```
Another than using Maven, which I don't want to or running ant xml manually, 
which I do, you can "fix" the GWT/eclipse problem by following the last post 
from the GWT forum  thread here.

https://groups.google.com/forum/#!topic/google-web-toolkit/e3DoVrI6V70

I tried it and it works.
```

Original comment by `colin.y....@gmail.com` on 29 Jul 2013 at 6:51
