### ISSUE TITLE
New / Create a Web Application project window is blank

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#237]
```
FOUND IN
(From: About Eclipse)
Eclipse Standard/SDK
Version: Kepler Release
Build id: 20130614-0229 

(From: Eclipse Installation details / Installed Software)
  Eclipse Standard/SDK  2.0.0.20130613-0530 epp.package.standard    null

  Google App Engine Java SDK 1.8.3  1.8.3   com.google.appengine.eclipse.sdkbundle.feature.feature.group

  Google Web Toolkit SDK 2.5.1  2.5.1   com.google.gwt.eclipse.sdkbundle.feature.feature.group

  GWT Designer  3.1.2.r37x201305212016  com.google.gdt.eclipse.designer.feature.feature.group

  GWT Designer Core 3.1.2.r37x201305212000  com.google.gdt.eclipse.designer.hosted.feature.feature.group

  GWT Designer Editor   3.1.2.r37x201305212009  com.google.gdt.eclipse.designer.editor.feature.feature.group

  GWT Designer GPE  3.1.2.r37x201303061641  com.google.gdt.eclipse.designer.gpe.feature.feature.group


Encountered on Win7.

PROBLEM DESCRIPTION:
starting a new (my first) project:
File - New - Other - Google - Web Application Project
Next - Next (must click Next 2x)

The 'New Web Application Project / Create a Web Application project' window is 
blank. The Back and Cancel buttons work but the Finish button (it's active) 
does nothing. Next is grayed. It's just an empty window and is only about half 
as high as the populated window should be.

No workaround.
No error message.
```

Original issue reported on code.google.com by `dpaul6...@gmail.com` on 4 Sep 2013 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
I am attaching a screen shot of the problem. I hope you can see that the window 
is blank. I have also installed all of the updates. The problem still exists. I 
can, however, create an Android project.
```

Original comment by `dpaul6...@gmail.com` on 4 Sep 2013 at 5:30

Attachments:
- [GWT problem.jpg](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-237/comment-1/GWT problem.jpg)

**Comment by GoogleCodeExporter** [comment]
```
Moving to the GPE issue tracker.
```

Original comment by `t.broyer` on 5 Sep 2013 at 8:19

**Comment by GoogleCodeExporter** [comment]
```
Do you see the com.google.gdt.eclipse.suite feature in your installation? What 
version is it?

Also, do you see any errors in your error log when you open the wizard (Window 
-> Show View -> Error Log). 
```

Original comment by `rdayal@google.com` on 5 Sep 2013 at 2:11

**Comment by GoogleCodeExporter** [comment]
```
Yes, com.google.gdt.eclipse.suite is an installed plugin as:

  Google Suite Plugin 3.3.0.v201307162142-rel-r37

Error log shows about 20 messages like you see below. The error log Message 
reads "Unhandled event loop exception". I copied one line of the error log and 
got all of the detail below when I did the paste.

eclipse.buildId=4.3.0.I20130605-2000
java.version=1.7.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product 
org.eclipse.epp.package.standard.product

Error
Wed Sep 04 13:38:09 EDT 2013
Unhandled event loop exception

java.lang.NullPointerException
    at com.google.gdt.eclipse.suite.wizards.NewWebAppProjectWizardPage.useGae(NewWebAppProjectWizardPage.java:329)
    at com.google.gdt.eclipse.suite.wizards.NewWebAppProjectWizard.performFinish(NewWebAppProjectWizard.java:104)
    at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:827)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:432)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:628)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)
    at org.eclipse.jface.window.Window.open(Window.java:802)
    at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:259)
    at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:279)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:243)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:224)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:167)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
    at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:420)
    at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:157)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

```

Original comment by `dpaul6...@gmail.com` on 6 Sep 2013 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
I have attached the entire error log...
```

Original comment by `dpaul6...@gmail.com` on 6 Sep 2013 at 5:08

Attachments:
- [ErrorLog_dpaul6463_9-6-13.txt](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-237/comment-5/ErrorLog_dpaul6463_9-6-13.txt)

**Comment by GoogleCodeExporter** [comment]
```
You installed the wrong version of GPE for your version of Eclipse. If the 
version of gdt.suite is  Google Suite Plugin 3.3.0.v201307162142-rel-r37, it 
means that you installed the Eclipse 3.7 version of GPE. It looks like you're 
actually running Eclipse 4.3. 

I'd recommend that you uninstall GPE completely, and afterwards, make sure that 
there are no plugins in your {eclipse_home}/plugins directory that start with 
com.google.gwt, com.google.gdt, or com.google.appengine. Remove them.

Then, install GPE folr Eclipse 4.3 from http://dl.google.com/eclipse/plugin/4.3
```

Original comment by `rdayal@google.com` on 10 Sep 2013 at 4:35
- Changed state: **Invalid**
