### ISSUE TITLE
DriveWritingException when saving eclipse project to Google Drive

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#284]
```
What steps will reproduce the problem?
1. Import a Google Apps Script project into eclipse (Kepler or Indigo)
2. Edit one of the files in the project
3. Try to save the file

What is the expected output? What do you see instead?
Error saving Eclipse project deleteme to Drive (file ID: 
1QjvCvWJ6oAqaE9ph0lCs9cVx0NSwLoPuVfxdqSSgfAD7XQ6351fOzXC5)

What version of the product are you using? On what operating system?
Eclipse (Kepler) on Windows 7 64-bit

eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product 
org.eclipse.epp.package.standard.product


Please provide any additional information below.

The problem started about 14 hours ago. I tried from both the Indigo release 
and the Kepler release of eclipse and see the same server error when the plugin 
attempts to save a file to Google drive

com.google.gdt.eclipse.drive.driveapi.DriveWritingException: Server error while 
storing project in Drive.
    at com.google.gdt.eclipse.drive.driveapi.DriveServiceFacade.writeProject(DriveServiceFacade.java:222)
    at com.google.gdt.eclipse.drive.DriveEclipseProjectMediator.performDriveUpdate(DriveEclipseProjectMediator.java:446)
    at com.google.gdt.eclipse.drive.DriveEclipseProjectMediator$2.run(DriveEclipseProjectMediator.java:406)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 
500 Internal Server Error
{
  "code" : 500,
  "errors" : [ {
    "domain" : "global",
    "message" : "Internal Error",
    "reason" : "internalError"
  } ],
  "message" : "Internal Error"
}
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:423)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at com.google.gdt.eclipse.drive.driveapi.DriveServiceFacade.writeProject(DriveServiceFacade.java:219)
    ... 5 more

```

Original issue reported on code.google.com by `yoa...@gmail.com` on 29 May 2014 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
I'm also experiencing this today.  Even if I create another project and 
reimport.  same thing happens. 
```

Original comment by `sen.vilo...@achievewithoutborders.com` on 29 May 2014 at 8:25

**Comment by GoogleCodeExporter** [comment]
```
Same problem here on Mac OS w/JRE 1.7 from Oracle.
```

Original comment by `jkhoff...@gmail.com` on 29 May 2014 at 5:21

**Comment by GoogleCodeExporter** [comment]
```
Same here
```

Original comment by `alejandr...@gmail.com` on 30 May 2014 at 12:46

**Comment by GoogleCodeExporter** [comment]
```
Same problem here. Problem just started occurring today.
```

Original comment by `dgvan...@gmail.com` on 30 May 2014 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
Same here.. using Mac OS.  I have been using the same Eclipse project a week 
before and this started coming up today 
```

Original comment by `anupshi...@gmail.com` on 30 May 2014 at 5:27

**Comment by GoogleCodeExporter** [comment]
```
Same problem.
```

Original comment by `shaun.do...@gmail.com` on 31 May 2014 at 5:46

**Comment by GoogleCodeExporter** [comment]
```
Same here using Ubuntu 12.04
```

Original comment by `vinaym...@gmail.com` on 1 Jun 2014 at 6:50

**Comment by GoogleCodeExporter** [comment]
```
Same :)
```

Original comment by `vroues...@gmail.com` on 1 Jun 2014 at 2:54

**Comment by GoogleCodeExporter** [comment]
```
Anyone who's resolved this issue from their side? If you've got a workaround, 
appreciate if you can share ;-)
```

Original comment by `roovin.e...@achievewithoutborders.com` on 2 Jun 2014 at 8:03

**Comment by GoogleCodeExporter** [comment]
```
Not really a workaround, but I've copied all the files to a local folder and 
use eclipse as an editor and copy/paste the entire file to the apps script 
editor running in my browser. it is tedious but it is better than using the 
apps script editor :)
```

Original comment by `yoa...@gmail.com` on 2 Jun 2014 at 9:14

**Comment by GoogleCodeExporter** [comment]
```
same issue
```

Original comment by `mikhail.zagorny` on 2 Jun 2014 at 1:24

**Comment by GoogleCodeExporter** [comment]
```
it's still happening.
```

Original comment by `youpi...@gmail.com` on 2 Jun 2014 at 10:18

**Comment by GoogleCodeExporter** [comment]
```
Why not implement google apps scripts on drive like a virtual folder, 
containing the gs and html files? isn't that the cleanest solution? 
There would be no need for eclipse plugins, and people could use any editor 
they like.. vim, emacs, textmate.. 

```

Original comment by `roberto....@bentobox.pro` on 5 Jun 2014 at 2:02

**Comment by GoogleCodeExporter** [comment]
```
no solution yet?
```

Original comment by `maarten....@gmail.com` on 7 Jun 2014 at 8:23

**Comment by GoogleCodeExporter** [comment]
```
anyone got around this problem yet?
```

Original comment by `yoa...@gmail.com` on 13 Jun 2014 at 7:26

**Comment by GoogleCodeExporter** [comment]
```
We are getting the same problem and had to stop using Eclipse plugin for
Apps Script editing.
Em 13/06/2014 04:26, <google-plugin-for-eclipse@googlecode.com> escreveu:
```

Original comment by `m...@nimbustecnologia.com.br` on 13 Jun 2014 at 10:47

**Comment by GoogleCodeExporter** [comment]
```
Yes, this bug is a show stopper, and using the online ide is slow and
unproductive (no customizable key bindings, no auto format, no 2 files
views...) and unmantainable (no git!)
Why cannot the javascript files be just.. you know.. files! Editable with
all the awesome ides already around!
The feature of "you cannot save if it doesn't compile" is just a placebo:
it's always javascript, so the real problems are runtime errors for type
unsafety rather than compile time syntax errors..

Roberto Previdi <roberto.previdi@bentobox.pro>

http://bentobox.pro
+39 045 4935960
Corso Milano 127 - Verona.




On Fri, Jun 13, 2014 at 12:47 PM, <google-plugin-for-eclipse@googlecode.com>
wrote:
```

Original comment by `roberto....@bentobox.pro` on 16 Jun 2014 at 11:23

**Comment by GoogleCodeExporter** [comment]
```
Please please please fix this!   With a large project (30k lines of code) 
manually copying files up to the online IDE is not a viable solution!!!


```

Original comment by `jdiam...@nydi.org` on 18 Jun 2014 at 12:00

**Comment by GoogleCodeExporter** [comment]
```
Error gone. Seems like Google team fixed it. Thanks!
```

Original comment by `roovin.e...@achievewithoutborders.com` on 19 Jun 2014 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
Seems to be working for me too now.
```

Original comment by `jdiam...@nydi.org` on 19 Jun 2014 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
Works for me too now.
```

Original comment by `yoa...@gmail.com` on 19 Jun 2014 at 6:36

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 27 Jun 2014 at 2:43
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Seems Bug is again happening.
```

Original comment by `sen.vilo...@achievewithoutborders.com` on 10 Jul 2014 at 2:27

**Comment by GoogleCodeExporter** [comment]
```
I see the following in the Error Log when the Eclipse plugin attempts to save:

Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 
400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid mime type provided",
    "reason" : "invalid"
  } ],
  "message" : "Invalid mime type provided"
}
```

Original comment by `yoa...@gmail.com` on 10 Jul 2014 at 11:55

**Comment by GoogleCodeExporter** [comment]
```
same

```

Original comment by `KokHin.C...@gmail.com` on 14 Jul 2014 at 6:53

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Same... Please fix this. 400 bad request in error log

```

Original comment by `rex.ying0923@gmail.com` on 14 Jul 2014 at 10:34

**Comment by GoogleCodeExporter** [comment]
```
same

com.google.gdt.eclipse.drive.driveapi.DriveWritingException: Server error while 
storing project in Drive.
    at com.google.gdt.eclipse.drive.driveapi.DriveServiceFacade.writeProject(DriveServiceFacade.java:222)
    at com.google.gdt.eclipse.drive.DriveEclipseProjectMediator.performDriveUpdate(DriveEclipseProjectMediator.java:446)
    at com.google.gdt.eclipse.drive.DriveEclipseProjectMediator$2.run(DriveEclipseProjectMediator.java:406)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 
400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid mime type provided",
    "reason" : "invalid"
  } ],
  "message" : "Invalid mime type provided"
}
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:423)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at com.google.gdt.eclipse.drive.driveapi.DriveServiceFacade.writeProject(DriveServiceFacade.java:219)
    ... 5 more

```

Original comment by `ad...@singong.net` on 17 Jul 2014 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
Same... Please fix this. 400 bad request in error log
```

Original comment by `vkornyl...@nravo.com` on 21 Jul 2014 at 11:14

**Comment by GoogleCodeExporter** [comment]
```
Please reopen this issue.
```

Original comment by `is...@ttj.gr.jp` on 21 Jul 2014 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
Same... Please fix this.
```

Original comment by `volko...@gmail.com` on 22 Jul 2014 at 8:24

**Comment by GoogleCodeExporter** [comment]
```
com.google.gdt.eclipse.drive.driveapi.DriveWritingException: Server error while 
storing project in Drive.
    at com.google.gdt.eclipse.drive.driveapi.DriveServiceFacade.writeProject(DriveServiceFacade.java:222)
    at com.google.gdt.eclipse.drive.DriveEclipseProjectMediator.performDriveUpdate(DriveEclipseProjectMediator.java:446)
    at com.google.gdt.eclipse.drive.DriveEclipseProjectMediator$2.run(DriveEclipseProjectMediator.java:406)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 
400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid mime type provided",
    "reason" : "invalid"
  } ],
  "message" : "Invalid mime type provided"
}
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:423)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at com.google.gdt.eclipse.drive.driveapi.DriveServiceFacade.writeProject(DriveServiceFacade.java:219)
    ... 5 more

```

Original comment by `vkornyl...@nravo.com` on 23 Jul 2014 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
I too have "Invalid mime type provided"

com.google.gdt.eclipse.drive.driveapi.DriveWritingException: Server error while 
storing project in Drive.
    at com.google.gdt.eclipse.drive.driveapi.DriveServiceFacade.writeProject(DriveServiceFacade.java:222)
    at com.google.gdt.eclipse.drive.DriveEclipseProjectMediator.performDriveUpdate(DriveEclipseProjectMediator.java:446)
    at com.google.gdt.eclipse.drive.DriveEclipseProjectMediator$2.run(DriveEclipseProjectMediator.java:406)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 
400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid mime type provided",
    "reason" : "invalid"
  } ],
  "message" : "Invalid mime type provided"
}
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:423)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at com.google.gdt.eclipse.drive.driveapi.DriveServiceFacade.writeProject(DriveServiceFacade.java:219)
    ... 5 more
```

Original comment by `p...@lucidchart.com` on 24 Jul 2014 at 9:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
same!

Eclipse Juno on Windows 7 64bit

I hope it will be fixed early, eclipse development is too better.

Integration with Version Control is unbeatable

Ciao!
```

Original comment by `l...@zzapps.nl` on 28 Jul 2014 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
Seems to be working now
```

Original comment by `m...@nimbustecnologia.com.br` on 13 Aug 2014 at 12:13

**Comment by GoogleCodeExporter** [comment]
```
Seems that the problem appeared today
```

Original comment by `salim.be...@gmail.com` on 10 Feb 2015 at 10:56

**Comment by GoogleCodeExporter** [comment]
```
same issue
```

Original comment by `weibogu1...@gmail.com` on 3 Nov 2015 at 11:30
