### ISSUE TITLE
GWT Compile button does nothing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#76]
```
What steps will reproduce the problem?
--------------------------------------

1. Create/import a GWT project
2. Select it
3. Click GWT Compile Project... in the toolbar

What is the expected output? What do you see instead?
-----------------------------------------------------

The compile dialog should open. Instead nothing happens.

What version of the product are you using? On what operating system?
--------------------------------------------------------------------

Eclipse 4.2.0
Google Plugin 3.0.1.v201206290132-rel-r42
Linux, Ubuntu 12.04

Please provide any additional information below.
------------------------------------------------

Caused by: java.lang.NullPointerException
    at com.google.gwt.eclipse.core.actions.GWTCompileToolbarHandler.execute(GWTCompileToolbarHandler.java:60)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:293)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    ... 42 more
```

Original issue reported on code.google.com by `bartvanh...@gmail.com` on 12 Jul 2012 at 9:09

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
This may be related, GWT Compile does not select the current project (same 
version of eclipse, same plugin version, but Windows 7):

1)  Right click on a project in Project Explorer
2)  Select Google -> GWT Compile

The Project: in the dialog will not necessarily be the selected project in the 
Project Explorer.
```

Original comment by `sean.dru...@frameworkplus.com` on 16 Jul 2012 at 5:16

**Comment by GoogleCodeExporter** [comment]
```
Adding this. I'm on Windows 7 Pro, I am getting the same error with the latest 
version.
```

Original comment by `Syion...@gmail.com` on 17 Aug 2012 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
Can you take a look at this one?
```

Original comment by `rdayal@google.com` on 4 Oct 2012 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
Fixed.
```

Original comment by `nbashirb...@google.com` on 19 Nov 2012 at 4:04

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 20 Nov 2012 at 11:15
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 19 Dec 2012 at 10:50
- Added labels: **Release-3.2**

**Comment by GoogleCodeExporter** [comment]
```
I have this issue with 3.2.0.v201302131858-rel-r42 (Juno SR2) on Windows 7
```

Original comment by `dam...@aeromac.com` on 19 Mar 2013 at 11:24

**Comment by GoogleCodeExporter** [comment]
```
I am using latest integration build of eclipse.  After about 3 compiles and 
some local debugging, first the toolbar 'GWT Compile Project' stops working, 
but the context "GWT Compile Project' from the project in the project browser 
still works.  Eventually that stops working too, and I need to restart.
```

Original comment by `ste...@spungin.tv` on 23 Mar 2013 at 11:26

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem, using   4.2 (3.2.1.v201303211244-rel-r42) in Eclipse 
4.2.2 (M20130204-1200). As a workaround, I have to close and re-open the 
project, then it works again. Context menu compilation is not affected.
```

Original comment by `harald.schilly` on 26 Mar 2013 at 2:08

**Comment by GoogleCodeExporter** [comment]
```
All of a sudden I'm having the same issue now?
No idea how and why it started. I did update the google plugin lately.

Google Plugin for Eclipse 4.2   3.2.4.v201306061638-rel-r42
```

Original comment by `arny...@gmail.com` on 25 Jun 2013 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
Hi there, I have the same issue (clicking the "GWT Compile" button nothing 
happens), I'm using Eclipse Version: Luna Release (4.4.0). Closing and 
reopening the project doesn't fix it, can somebody suggest me how to fix this 
issue? Thx

```

Original comment by `Ventro...@gmail.com` on 13 Jul 2014 at 7:04

**Comment by GoogleCodeExporter** [comment]
```
Same issue:

Win 7 x64
Eclipse Luna 4.4.0
GWT 2.6.0
```

Original comment by `vitr...@gmail.com` on 30 Sep 2014 at 12:57
