### ISSUE TITLE
Cloud Endpoint using GWT generates errors on build

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#90]
```
Not sure if anyone else is seeing this error, but since upgrading to the latest 
GPE version in November (2012), I have been seeing this error intermittently 
roughly two thirds of the time when I try to run an AppEngine project in 
Eclipse.

What steps will reproduce the problem?
1. Run (or build) an AppEngine project in Eclipse.

What is the expected output? What do you see instead?
Project should run (or build) normally.
Instead I see the error shown in the attached image, roughly two thirds of the 
time.
NOTE: The error in the image is straight from a fresh copy of a GWT sample 
project from googlecode. New project vs. old project, does not seem to matter.

What version of the product are you using? On what operating system?
I have Google Eclipse Plugin version 3.1.2v201211121240-rel-r42, running 
Eclipse Juno 4.2 SR1(20121004-1855). AppEngine SDK version 1.7.3. GWT SDK 
version 2.5.0.

Please provide any additional information below.
- I am running a team of ~20 developers and no one else is seeing this problem. 
We all work on the same set of projects.
- I have already tried grabbing a fresh copy of Eclipse and reinstalling all my 
plugins. Didn't help.
- I have already tried setting up a brand new workspace folder and migrating 
all my projects there instead. Same problem.


```

Original issue reported on code.google.com by `vi...@umich.edu` on 17 Nov 2012 at 8:35

Attachments:
- [Error - Google AppEngine Project Change Notifier.png](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-90/comment-0/Error - Google AppEngine Project Change Notifier.png)

**Comment by GoogleCodeExporter** [comment]
```
As a temporary workaround, navigate to Project Properties -> Builders and 
disable the "Google App Engine Change Notifier" builder.

Can you navigate to the Error log (Window -> Show View -> Error Log) and tell 
me what exceptions show up in the log around the time that you hit this error?
```

Original comment by `rdayal@google.com` on 19 Nov 2012 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
Hello,
 The workaround is great. Thank you for that! This has been driving me crazy.

Here is the exception that shows up in the error log, along with its stack 
trace.
Let me know if you need anything else.



java.lang.ExceptionInInitializerError
    at com.google.appengine.repackaged.org.codehaus.jackson.map.deser.StdDeserializerProvider.<init>(StdDeserializerProvider.java:89)
    at com.google.appengine.repackaged.org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:391)
    at com.google.appengine.repackaged.org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:358)
    at com.google.appengine.repackaged.org.codehaus.jackson.map.ObjectMapper.<init>(ObjectMapper.java:328)
    at com.google.api.server.spi.ObjectMapperUtil.createStandardObjectMapper(ObjectMapperUtil.java:30)
    at com.google.api.server.spi.tools.AnnotationApiConfigGenerator.<clinit>(AnnotationApiConfigGenerator.java:176)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmApiCreator.createSwarmApi(SwarmApiCreator.java:97)
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmServiceCreator.create(SwarmServiceCreator.java:192)
    at com.google.gdt.eclipse.appengine.swarm.wizards.HandleGaeProjectChange.gaeProjectRebuilt(HandleGaeProjectChange.java:64)
    at com.google.appengine.eclipse.core.properties.ui.GaeProjectChangeNotifier.build(GaeProjectChangeNotifier.java:77)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:513)
    at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:432)
    at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:305)
    at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.lang.NullPointerException
    at sun.net.util.URLUtil.urlNoFragString(URLUtil.java:29)
    at sun.misc.URLClassPath.getLoader(URLClassPath.java:292)
    at sun.misc.URLClassPath.getResource(URLClassPath.java:168)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:194)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at com.google.appengine.repackaged.org.codehaus.jackson.map.deser.BasicDeserializerFactory.<clinit>(BasicDeserializerFactory.java:66)
    ... 30 more

```

Original comment by `vi...@umich.edu` on 20 Nov 2012 at 7:29

**Comment by GoogleCodeExporter** [comment]
```
Thanks, we'll look into this. One other thing that would be helpful - can you 
list the libs that are on your App Engine Project's build path, and the libs 
that are in it's war/WEB-INF/lib folder?
```

Original comment by `rdayal@google.com` on 20 Nov 2012 at 11:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 20 Nov 2012 at 11:09
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Sure thing...

The simplest case where I see this behavior was in the "Contacts" sample app 
for GWT: 
http://code.google.com/p/google-web-toolkit/downloads/detail?name=Tutorial-hello
mvp-2.1.zip

I attached an image of the lib folder contents, and I pasted the .classpath 
file below. Hope that helps.

<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="src" path="src"/>
    <classpathentry kind="src" path="test"/>
    <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
    <classpathentry kind="con" path="com.google.gwt.eclipse.core.GWT_CONTAINER/GWT"/>
    <classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/3"/>
    <classpathentry kind="lib" path="lib/easymock-2.5.2.jar"/>
    <classpathentry kind="con" path="com.google.appengine.eclipse.core.GAE_CONTAINER"/>
    <classpathentry kind="output" path="war/WEB-INF/classes"/>
</classpath>



```

Original comment by `vi...@umich.edu` on 21 Nov 2012 at 12:04

Attachments:
- [lib_folder.PNG](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-90/comment-5/lib_folder.PNG)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the information. I think the problem is happening due to GWT being 
present, though we're still investigating why it's causing a problem. I've 
updated the summary accordingly We'll definitely fix this in the next release, 
and if I can find a workaround, I'll let you know.
```

Original comment by `rdayal@google.com` on 21 Nov 2012 at 3:36
- Changed title: **Cloud Endpoint using GWT generates errors on build**

**Comment by GoogleCodeExporter** [comment]
```
Thank you.
```

Original comment by `vi...@umich.edu` on 21 Nov 2012 at 12:25

**Comment by GoogleCodeExporter** [comment]
```
I am receiving the same NO_MODIFICATION_ALLOWED_ERR exception. I have attached 
additional info that I hope will help to track down this bug. But my error log 
stacktrace seems to point to a org.w3c.dom.DOMException.

(See Attached Error Log)



Eclipse Platform (Juno)
Version: 4.2.0.v20120608-135145-9JF7BHV8FyMteji0Oi_ePMz0xuZ8TVo7lV0z0ecb
Build id: I20120608-1400

GPE 3.1.0v201208080121-rel-r42

App Engine SDK 1.7.0

GWT SDK 2.5.0
```

Original comment by `jren...@continuityconsulting.com` on 6 Dec 2012 at 12:16

Attachments:
- [Error_Log.log](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-90/comment-8/Error_Log.log)
- [lib-contents.png](https://storage.googleapis.com/google-code-attachments/google-plugin-for-eclipse/issue-90/comment-8/lib-contents.png)

**Comment by GoogleCodeExporter** [comment]
```
Thx for the information on the NO_MODIFICATION_ALLOWED_ERR exception. I suspect 
we're doing something wrong in our DOM manipulation code. Can you post your 
web.xml file?
```

Original comment by `rdayal@google.com` on 10 Dec 2012 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
Hi, I am experiencing a similar problem and it seems to be related so I'm 
posting here. I think there's an issue how Google App Engine Project Change 
Notifier interprets .classpath's source folders.

I added an additional source folder to my project by modifying the .classpath 
and added a source folder like so:

<classpathentry kind="src" path="src/test/java"/>

Now, once I recompile the source in Eclipse by doing Project -> Clean, I get 
the following exception:

Errors occurred during the build.
Errors running builder 'Google App Engine Project Change Notifier' on project 
java.lang.ExceptionInInitializerError.

When I refresh the project and remove the source folder declaration from the 
.classpath, the problem goes away. This was found in the following build

  Google App Engine Java SDK 1.7.3  1.7.3   com.google.appengine.eclipse.sdkbundle.feature.feature.group

```

Original comment by `dlawogus...@gmail.com` on 15 Dec 2012 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
@diawogus: Thanks for the tip; it totally seems to be related to the presence 
of the additional source folder. I have absolutely no idea as to why that 
matters; I'm looking into this.
```

Original comment by `rdayal@google.com` on 18 Dec 2012 at 9:49

**Comment by GoogleCodeExporter** [comment]
```
I have a feeling that when we construct the classpath for the classloader (to 
load up the SwarmServiceCreator), we're generating a null reference in the 
array of classloader URLs. Looking into it..
```

Original comment by `rdayal@google.com` on 18 Dec 2012 at 11:42

**Comment by GoogleCodeExporter** [comment]
```
Found the problem; a null reference is being placed in the array of classloader 
URLs. We have a fix for the problem. We'll release this in GPE 3.2 (mid-Jan).

If people want the fix for this pushed sooner, star this bug and we'll do it. 
```

Original comment by `rdayal@google.com` on 19 Dec 2012 at 10:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 19 Dec 2012 at 10:46
- Added labels: **GPE3.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 19 Dec 2012 at 10:48
- Added labels: **Release-3.2**
- Removed labels: **GPE3.2**

**Comment by GoogleCodeExporter** [comment]
```
Hi Dayal,
I'm glad you found the problem and fixed it. I look forward to seeing the fix 
when it's released. Have a great holidays!
```

Original comment by `j...@visitscan.com` on 20 Dec 2012 at 6:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 3 Jan 2013 at 10:17
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Problem still occurring in 3.2. 

What version of the product are you using? On what operating system?
Google Suite Plugin 3.2.0.v2013021131858-rel-r42
AppEngine SDK 1.7.5
Eclipse Juno Service Release 1 Build id: 20121004-1855
JDK 1.7.0_09
Mac OSX 10.8.2

Exception Details:
org.w3c.dom.DOMException: NO_MODIFICATION_ALLOWED_ERR: An attempt is made to 
modify an object where modifications are not allowed.
    at com.sun.org.apache.xerces.internal.dom.ParentNode.internalInsertBefore(ParentNode.java:351)
    at com.sun.org.apache.xerces.internal.dom.ParentNode.insertBefore(ParentNode.java:288)
    at com.sun.org.apache.xerces.internal.dom.NodeImpl.appendChild(NodeImpl.java:238)
    at com.google.gdt.eclipse.appengine.swarm.util.XmlUtil.insertSystemServiceServlet(XmlUtil.java:458)
    at com.google.gdt.eclipse.appengine.swarm.util.XmlUtil.updateWebXml(XmlUtil.java:176)
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmServiceCreator.create(SwarmServiceCreator.java:312)
    at com.google.gdt.eclipse.appengine.swarm.wizards.HandleGaeProjectChange.gaeProjectRebuilt(HandleGaeProjectChange.java:75)
    at com.google.appengine.eclipse.core.properties.ui.GaeProjectChangeNotifier.build(GaeProjectChangeNotifier.java:88)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

```

Original comment by `dean.bar...@gmail.com` on 14 Feb 2013 at 10:52

**Comment by GoogleCodeExporter** [comment]
```
ok, I think we fixed the first part of the problem, but the second part of the 
problem needs to be addressed. See here:

http://code.google.com/p/google-plugin-for-eclipse/issues/detail?id=102

We'll leave this one as closed, but put your comments about the 
NO_MODIFICATION_ALLOWED error in issue 102.
```

Original comment by `rdayal@google.com` on 20 Feb 2013 at 2:42

**Comment by GoogleCodeExporter** [comment]
```
Same problem. Please help.

Message:
Errors running builder 'Google App Engine Project Change Notifier' on project 
'<project name>'.

Exception Stack Trace:
java.lang.NullPointerException
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmServiceCreator.deleteAllConfigs(SwarmServiceCreator.java:454)
    at com.google.gdt.eclipse.appengine.swarm.wizards.helpers.SwarmServiceCreator.create(SwarmServiceCreator.java:312)
    at com.google.gdt.eclipse.appengine.swarm.wizards.HandleGaeProjectChange.gaeProjectRebuilt(HandleGaeProjectChange.java:75)
    at com.google.appengine.eclipse.core.properties.ui.GaeProjectChangeNotifier.build(GaeProjectChangeNotifier.java:88)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:629)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:172)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:203)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:255)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:258)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:362)
    at org.eclipse.core.internal.resources.Project$1.run(Project.java:545)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1975)
    at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:524)
    at org.eclipse.core.internal.resources.Project.build(Project.java:115)
    at com.google.gdt.eclipse.core.BuilderUtilities$2.runInWorkspace(BuilderUtilities.java:202)
    at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Session Data:
eclipse.buildId=M20110210-1200
java.version=1.6.0_27
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.reporting.product
Command-line arguments:  -data /home/renfeng/workspace-truemuze -os linux -ws 
gtk -arch x86_64 -product org.eclipse.epp.package.reporting.product


```

Original comment by `renfeng...@gmail.com` on 8 Apr 2013 at 2:54

**Comment by GoogleCodeExporter** [comment]
```
@nhcohen: Can you open a new bug for the problem mentioned at comment #20 and 
look into the problem? appu can help you out with this.
```

Original comment by `rdayal@google.com` on 8 Apr 2013 at 2:57

**Comment by GoogleCodeExporter** [comment]
```
Certainly. Give me some time to reduce it to a test case.


On Mon, Apr 8, 2013 at 10:57 PM,
<google-plugin-for-eclipse@googlecode.com>wrote:
```

Original comment by `renfeng...@gmail.com` on 8 Apr 2013 at 3:08

**Comment by GoogleCodeExporter** [comment]
```
Here is the new issue,
https://code.google.com/p/google-plugin-for-eclipse/issues/detail?id=116
```

Original comment by `renfeng...@gmail.com` on 8 Apr 2013 at 3:51

**Comment by GoogleCodeExporter** [comment]
```
1
```

Original comment by `poenar.ioana.harivuln` on 26 May 2015 at 11:31
