### ISSUE TITLE
Null Pointer in content assist for GWT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tsaiyilien/google-plugin-for-eclipse#97]
```
What steps will reproduce the problem?
1. Use eclipse juno.
2. Install groovy plugin from Groovy Update Site For Eclipse 4.2 - 
http://dist.codehaus.org/groovy/distributions/greclipse/snapshot/e4.2

  Groovy Compiler 1.7.10 Feature
  Groovy Compiler 1.8 Feature
  Groovy Compiler 2.0 Feature
  Groovy-Eclipse Feature
    Groovy-Eclipse Headless Feature
    JDT Core patch for Groovy-Eclipse plugin
  Groovy-Eclipse M2E integration
  Groovy-Eclipse M2E integration (Source code)
  Groovy-Eclipse Sources Feature
  Groovy-Eclipse Test Sources Feature
  Groovy-Eclipse Tests Feature

3. Install GWT plugin 2.5 and google plugin

4. Create a Groovy Project.
5. Create Simple groovy script:
def func(){
    String s = "string";


}

6. Inside function "func" enter "s." to trigger content assist.
  Dialog appears stating that the content assist failed and to disable Basic Proposals. 
I do not wish to disable Basic Proposals because it breaks the content assist 
for the groovy plugin.

There is a NullPointerException:


!ENTRY org.eclipse.jdt.ui 2 0 2013-01-10 08:28:14.870
!MESSAGE The 'com.google.gwt.eclipse.core.jsniCompletionProposalComputer' 
proposal computer from the 'com.google.gwt.eclipse.core' plug-in did not 
complete normally. The extension has thrown a runtime exception.
!STACK 0
java.lang.NullPointerException
    at com.google.gwt.eclipse.core.editors.java.JsniMethodBodyCompletionProposalComputer.computeCompletionProposals(JsniMethodBodyCompletionProposalComputer.java:272)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:333)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:328)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:284)
    at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1839)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:566)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:563)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:498)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:492)
    at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:378)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4144)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1022)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:916)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:585)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:540)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
```

Original issue reported on code.google.com by `carl.par...@lattix.com` on 10 Jan 2013 at 1:35

**Comment by GoogleCodeExporter** [comment]
```
The 'com.google.gwt.eclipse.core.jsniCompletionProposalComputer' proposal 
computer from the 'com.google.gwt.eclipse.core' plug-in did not complete 
normally. The extension has thrown a runtime exception.



java.lang.NullPointerException
    at com.google.gwt.eclipse.core.editors.java.JsniMethodBodyCompletionProposalComputer.computeCompletionProposals(JsniMethodBodyCompletionProposalComputer.java:272)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:333)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:328)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:284)
    at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1839)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:566)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:563)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:498)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:492)
    at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:378)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3944)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3621)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1022)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:916)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:585)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:540)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)


eclipse.buildId=I20120608-1400
java.version=1.6.0_37
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring 
/Users/CFM/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product 
org.eclipse.epp.package.jee.product -keyring /Users/CFM/.eclipse_keyring 
-showlocation
```

Original comment by `sever...@gmail.com` on 26 Feb 2013 at 10:38

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 5 Mar 2013 at 6:44
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
The error also occurs if you don't install the GWT Toolkit SDK plugin.
```

Original comment by `UnPlan2nedApps` on 26 May 2013 at 8:44

**Comment by GoogleCodeExporter** [comment]
```
Also happening in Eclipse Kepler with the GWT plugin from 
http://dl.google.com/eclipse/plugin/4.3 (with or without GWT Toolkit SDK 
plugin) when Groovy-Eclipse is installed.
```

Original comment by `sean.flanigan@gmail.com` on 4 Sep 2013 at 2:14

**Comment by GoogleCodeExporter** [comment]
```
Looks like we need to disable the completion proposals for groovy scripts...not 
sure why we are even analyzing them. 
```

Original comment by `rdayal@google.com` on 4 Sep 2013 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
I meet it too。I try many eclipse,just when groovy and google cloud plugin 
installed,it happens.
```

Original comment by `sdznyan@gmail.com` on 31 Dec 2013 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
Any ETA on this?
```

Original comment by `casu...@gmail.com` on 6 Jan 2014 at 6:15

**Comment by GoogleCodeExporter** [comment]
```
In your project, have you applied the GWT Nature? Or is this just a Groovy 
Project, with no GWT?
```

Original comment by `rdayal@google.com` on 9 Jan 2014 at 3:17

**Comment by GoogleCodeExporter** [comment]
```
In my case, plain old project, no GWT.
```

Original comment by `casu...@gmail.com` on 9 Jan 2014 at 3:30

**Comment by GoogleCodeExporter** [comment]
```
Ok, we'll get this into the next release. 
```

Original comment by `rdayal@google.com` on 9 Jan 2014 at 6:05

**Comment by GoogleCodeExporter** [comment]
```
Is there any way to work around this until is resolved ? This completely 
destroys my working env.
```

Original comment by `horia.mu...@gmail.com` on 12 Nov 2014 at 8:41

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 12 Nov 2014 at 3:15

**Comment by GoogleCodeExporter** [comment]
```
Same problem here! Has this bug been resolved? Cannot use groovy!
```

Original comment by `navi...@di.uniroma1.it` on 25 Apr 2015 at 4:40
